name: 📦 Release (GitHub)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.CI_WRITE_TOKEN }}
          fetch-depth: 0

      - name: ⚙️ Install bun
        uses: oven-sh/setup-bun@v2

      - name: 🔨 Config git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: 📦 Release
        run: bunx --package @airfleet/wordpress-dev afwp release github --ci --verbose --replace-version
        env:
          GITHUB_TOKEN: ${{ secrets.CI_WRITE_TOKEN }}
